name: farm_wise_frontend
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^9.0.0
  email_validator: ^2.1.17
  image_picker: ^1.0.0
  http: ^1.1.0
  flutter_riverpod: ^2.3.6
  csc_picker: ^0.2.7
  mime_type: ^1.0.0
  http_parser: ^4.0.2
  themed: ^4.0.0
  shared_preferences: ^2.2.0
  razorpay_flutter: ^1.3.5
  logger: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "lib/assets/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/logo.png
    - lib/assets/images/logo2.png
    - lib/assets/images/background.jpg
    - lib/assets/images/background2.jpg
    - lib/assets/images/order1.png
    - lib/assets/images/product2.png
    - lib/assets/images/search2.png
    - lib/assets/images/pendingorder1.png
    - lib/assets/images/activeorders1.png
    - lib/assets/images/flaggedorders1.png
    - lib/assets/images/favorite11.png
    - lib/assets/images/ordershistory1.png
    - lib/assets/images/reviewpostedbyyou1.png
    - lib/assets/images/reviewpostedforyou1.png
    - lib/assets/images/listeditems1.png
    - lib/assets/images/nofilterproducts1.png